### ISSUE TITLE
Communication between js and php

### ISSUE THREAD

**Issue by kaczor6418** [kaczor6418/Party_Maker#13]
- [x] - js
- [x] - php

**Comment by MaciejNowacki** [comment]
@kaczor6418 

		if(empty($name) || empty($surname) || empty($email) || empty($birth) || empty($username) || empty($password))
		{
			echo json_encode(array('error' => array('info' => 'Wypełnij wszystkie pola!')));
			die();
		}
		
		if(!isDate($birth))
		{
			echo json_encode(array('error' => array('info' => 'odałeś niepoprawną datę. Format: DD/MM/RRRR', 'errorObj' => 'birthDate')));
		}
		
		if(strlen($name) < 3)
		{
			echo json_encode(array('error' => array('info' => 'Twoje imię nie może mieć mniej niż 3 znaki', 'errorObj' => 'name')));
		}
		
		if(strlen($surname) < 3)
		{
			echo json_encode(array('error' => array('info' => 'Twoje nazwisko nie może mieć mniej niż 3 znaki', 'errorObj' => 'surname')));
		}
		
		if(!filter_var($email, FILTER_VALIDATE_EMAIL))
		{
			echo json_encode(array('error' => array('info' => 'Podane adres email jest niepoprawny!', 'errorObj' => 'email')));
		}
		
		if(strlen($username) < 3)
		{
			echo json_encode(array('error' => array('info' => 'Nazwa użytkownika nie może być krótsza niż 3 znaki', 'errorObj' => 'username')));
		}
		
		if(strlen($password) < 8)
		{
			echo json_encode(array('error' => array('info' => 'Twoje hasło musi mieć minimum 8 znaków', 'errorObj' => 'password')));
		}

**Comment by kaczor6418** [comment]
Elo daj mi znac czy mozesz mi wysalc errorFields jako tablice a nie ciag skroci to moj kod o 2 linjki ;)

**Comment by MaciejNowacki** [comment]
No spoko, i tak w aktualnej wersji dopiero parsuje to na stringa pod koniec.
