### ISSUE TITLE
Complete sketch of database

### ISSUE THREAD

**Issue by kaczor6418** [kaczor6418/Party_Maker#6]

**Comment by MaciejNowacki** [comment]
@kobold97 W tabeli users zrób kolumny: id(A-I), login, password(255), name, surname, lastSuccessfulLogin, regDate, birthDate, attempts, lastUnsuccessfulLogin (data ostatniej nieudanej próby logowania). Typów się domyśl :P

**Comment by MaciejNowacki** [comment]
@kobold97 
default attempts = 0;
add column email
change DATE to TIMESTAMP in: lastActive, lastUnsuccessfulLogin, lastSuccessfulLogin, regDate

**Comment by MaciejNowacki** [comment]
@kobold97 
zrób jeszcze kolumnę avatar (VARCHAR(255)) i adres IP (VARCHAR(16)) w tabeli Users.

**Comment by MaciejNowacki** [comment]
@kobold97 
**events:**
- 	event_id
- 	creator_id
- 	nameEvent
- 	descEvent
- 	dateEvent
- 	locEvent (location, pewnie string(?))
- 	logoEvent (pewnie jakiś hash obrazka, więc VARCHAR(255))

**participantsEvent:**
- 	info_id (mało potrzebne, ale musi być)
- 	event_id
- 	participant_id
- 	status (w sumie nie wiem czy będą jakieś statusy, ale dodaj; zapewne jakiś mały int)

**postsInEvent:**
- 	post_id
- 	event_id
- 	postCreatorId
- 	postText (jakiś duży VARCHAR)
- 	postDate

	
**commentsInEvent:**
- 	comment_id
- 	event_id
- 	commentCreatorId
- 	commentText (jakiś duży VARCHAR)
- 	commentDate

**Comment by MaciejNowacki** [comment]
Dodać obsługę polskich znaków.

**Comment by MaciejNowacki** [comment]
Czekam na jakąś fajną kwerendę z jakimś równie zajebistym joinem, żeby:
pobrać informacje na temat eventu (event_id, nameEvent, descDevent, dateEvent, locEvent, logoEvent), w którym będzie brał udział jakiś participant_id.

**Comment by kobold97** [comment]
Kurwa typie, co to ma być??

**Comment by MaciejNowacki** [comment]
Co? Masz po prostu to zrobić, nie ma dyskusji.

**Comment by MaciejNowacki** [comment]
GDZIE MOJE QUERY I TABELA commentsInEvent??

**Comment by kobold97** [comment]
Wypierdalaj kurwa!

**Comment by MaciejNowacki** [comment]
Kultury choć trochę..

**Comment by MaciejNowacki** [comment]
@kobold97 dej unique do email varchar(255) NOT NULL,

**Comment by MaciejNowacki** [comment]
Zrób nową tabelę z kategoriami (category_id, nameOfCategory) i później dodaj klucz obcy do events category czy coś w ten deseń.
